# Generated by Django 6.0.3 on 2026-03-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('appointment_datetime', models.DateTimeField(blank=True, null=True)),
                ('lead_source', models.CharField(blank=True, max_length=255)),
                ('lead_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('salvage_notes', models.TextField(blank=True)),
                ('deal_stage', models.CharField(blank=True, max_length=255)),
                ('sales_rep', models.CharField(blank=True, max_length=255)),
                ('setter', models.CharField(blank=True, max_length=255)),
                ('sales_team', models.CharField(blank=True, max_length=255)),
                ('is_blitz_deal', models.BooleanField(default=False)),
                ('is_self_set', models.BooleanField(default=False)),
                ('stage_category', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CxProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('job_status', models.CharField(blank=True, max_length=255)),
                ('installer', models.CharField(blank=True, max_length=255)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('install_completed', models.DateField(blank=True, null=True)),
                ('inspection_scheduled', models.DateField(blank=True, null=True)),
                ('inspection_passed', models.DateField(blank=True, null=True)),
                ('pto_submitted', models.DateField(blank=True, null=True)),
                ('pto_approved', models.DateField(blank=True, null=True)),
                ('review_captured_date', models.DateField(blank=True, null=True)),
                ('testimonial_potential', models.BooleanField(default=False)),
                ('testimonial_done', models.BooleanField(default=False)),
                ('model_home_program', models.BooleanField(default=False)),
                ('has_review', models.BooleanField(default=False)),
                ('days_install_to_inspection_passed', models.IntegerField(blank=True, null=True)),
                ('days_install_to_pto_submitted', models.IntegerField(blank=True, null=True)),
                ('days_install_to_pto_approved', models.IntegerField(blank=True, null=True)),
                ('days_install_to_review', models.IntegerField(blank=True, null=True)),
                ('days_inspection_scheduled_to_passed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('canvasser', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('appt_time', models.DateTimeField(blank=True, null=True)),
                ('is_contact', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('sales_rep', models.CharField(blank=True, max_length=255)),
                ('sales_team', models.CharField(blank=True, max_length=255)),
                ('installer', models.CharField(blank=True, max_length=255)),
                ('lead_source', models.CharField(blank=True, max_length=255)),
                ('job_status', models.CharField(max_length=255)),
                ('project_category', models.CharField(max_length=64)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('customer_since', models.DateField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('on_hold_reason', models.CharField(blank=True, max_length=255)),
                ('is_clean_deal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('payload', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
