# Generated by Django 4.2.30 on 2026-04-07 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_project_pipeline_milestones'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardDataScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_kind', models.CharField(choices=[('team', 'Single sales team'), ('teams', 'Multiple sales teams'), ('rep', 'Single sales rep')], default='rep', max_length=16)),
                ('sales_team', models.CharField(blank=True, max_length=255)),
                ('sales_rep', models.CharField(blank=True, max_length=255)),
                ('sales_teams', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_scope', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard data scope',
                'verbose_name_plural': 'Dashboard data scopes',
            },
        ),
    ]
